const SUPABASE_URL = "https://yvoipikqffeipmkldfdx.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInRyaXAiOiJKV1QifQ.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2b2lwaWtxZmZlaXBta2xkZmR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzEzMzYsImV4cCI6MjA2ODM0NzMzNn0.o00mebj9FaHBb2YrKe8r7JN-fBEyYrnDZhlpAZO-dK0";

const supaClient = supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
